### ISSUE TITLE
install: cannot stat '/home/alarm/.cache/yay/cros-container-guest-tools-git/src/cros-container-guest-tools/cros-host-fonts/05-cros-fonts.conf': No such file or directory

### ISSUE THREAD

**Issue by BenjaminWegener** [mbkulik/cros-guest-tools#1]
on arch -> yay -S cros-container-guest-tools-git

install: cannot stat '/home/alarm/.cache/yay/cros-container-guest-tools-git/src/cros-container-guest-tools/cros-host-fonts/05-cros-fonts.conf': No such file or directory

-> File was deleted in last commit: https://chromium.googlesource.com/chromiumos/containers/cros-container-guest-tools/+/b933792566dcff3b23b5ef7b4b920d794b8bf2ef

I had to manually create it with following content:
```
<?xml version="1.0"?><fontconfig>
    <dir>/mnt/chromeos/fonts</dir>
</fontconfig>
```

**Comment by mbkulik** [comment]
I have updated the spec file for how host fonts are now mounted in the container (via a bind-mount). You can find the changes in the this branch, [https://github.com/mbkulik/cros-guest-tools/tree/host-fonts-changes](https://github.com/mbkulik/cros-guest-tools/tree/host-fonts-changes). 

The host-fonts-changes branch builds and installs without issues in a fedora container, but I do not have access to ChromeOS device right now to test if these changes are correct. I will be able to test the packages more thoroughly this weekend.

**Comment by BenjaminWegener** [comment]
thanks
